"use client" ;
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import"bootstrap-icons/font/bootstrap-icons.css";
import Navbar from "./Components/Navbar";
import {  useEffect } from "react";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    typeof document !== undefined &&
      require('bootstrap/dist/js/bootstrap.bundle.min.js');
  }, []);

  return (
    <html lang="en">
      <head>
        <title>Anuj | Portfolio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body >
      
          <div className="universal-container">

          <Navbar />
          <main>{children}</main>
          </div>
     
      </body>
    </html>
  );
}
